### PR TITLE
decode jwt in frontend

### PR DESCRIPTION
**Pull request by oscrx**

### CODE REVIEW

**Review by Mightybeardedking — APPROVED** [review]
Ja best joh

**Review by NvdLaan — CHANGES_REQUESTED** [review]
No

**Comment by Mightybeardedking** [comment]
JawelOp 13 feb. 2021 17:52 schreef NvdLaan <notifications@github.com>:
@NvdLaan requested changes on this pull request.

No

**Comment by oscrx** [comment]
it is done

**Comment by Mightybeardedking** [comment]
SpamOp 13 feb. 2021 17:59 schreef Oscar Wieman <notifications@github.com>:
it is done

**Pull request merged**
